test_case:
  manufacturer:
    - 新增厂商
    - 更新厂商信息
    - 更新厂商信息
    - 生产商-启用/禁用
    - 根据id获取厂商详情
    - 分页获取厂商列表
    - 获取厂商列表
    - 根据供应商id获取厂商列表

  manufacturerAuthorizations:
    - 根据id获取授权书详情
    - 分页获取授权书列表
    - 添加供应商授权书
    - 修改供应商授权书
    - 启用授权书
    - 禁用授权书
    - 获取授权书中的商品信息
    - 获取授权书列表
    - 根据厂商id和供应商id获取授权书列表


  CreateDepartments:
    - 新增科室
    - 更新科室信息
    - 批量绑定商品和科室
    - 移除科室商品
    - 根据id获取组织详情
    - 分页获取直接子节点组织列表
    - 获取组织树列表
    - 根据id获取父级组织
    - 分页查询科室商品
    - 导出科室商品
    - 设置仓库商品上下限
    - 修改仓库商品上下限
    - 删除仓库商品上下限
    - 设置科室商品并设置上下限
    - 查询仓库商品列表
    - 获取可以访问的非一级科室的科室名称和id
    - 获取所有非一级科室的科室名称和id
    - 获取所有科室(包含一级科室)的科室名称和id
    - 解绑商品和部门
    - 删除科室
  DistributionUnit_orderUnit:
    - 新建配送单位
    - 更新配送单位
    - 设置默认配送单位
    - 清空默认配送单位
    - 删除配送单位
    - 配送单位列表查询
    - 新建订货单位
    - 更新订货单位
    - 设置默认订货单位
    - 清空默认订货单位
    - 删除订货单位
    - 订货单位列表查询
  System:
    - 判断是否已登录
    - 查询所有字典数据
    - 查询某个字典类别
    - 根据字典类型查询某个字典类别
    - 查询所有字典类别
    - 查询所有字典类别(返回id和name)
    - 查询所有字典类别(返回name和value)
    - 获取所有省份
    - 根据areaCode获取下级区域
    - 根据areaCode获取同级区域
    - 按顺序返回areaCode父层区域路径
    - 一键审批
    - 获取图形验证码
    - 验证图形验证码是否正确
    - 查询所有2012类别
    - 查询所有2018类别
    - 配置列表，可根据查询条件
    - config 可选择字段
    - 自动生成加工单
    - 测试触发生成计划
    - 自动生成结算单
    - 自动波次
    - 自动生成历史库存
    - 自动检查部门退货
    - 加载处理失败的消息
    - 重新发送失败的消息
    - 加载打印信息
    - 批量加载打印信息
    - 标记打印成功
  consume_01:
    - 批量消耗
    - 扫码消耗
    - 查询物资（商品、套包）
    - 查询并消耗
    - 分页查询商品消耗记录
    - 导出商品消耗记录
    - 分页查询定数包消耗记录
    - 导出定数包消耗记录
    - 分页查询手术套包消耗记录
    - 导出手术套包消耗记录
    - 查询消耗记录详情
    - 扫码反消耗
    - 查询商品反消耗记录
    - 查询定数包反消耗记录
    - 查询手术套包反消耗记录
    - 导出商品反消耗记录
    - 导出定数包反消耗记录
    - 导出手术套包反消耗记录
    - 查询定数包反消耗明细
    - 查询手术套包反消耗明细
  consume_02:
    - 批量扫码反消耗
  custodian_01:
    - 新增一级供应商
    - 更新一级供应商
    - 启用/禁用
    - 根据id获取一级供应商详情
    - 分页获取一级供应商列表
    - 获取可用的一级供应商
    - 设置一级供应商账期
  goodsRequest_01:
    - 新增普通请领
    - 查询普通请领列表
    - 查询普通请领明细
    - 修改普通请领
    - 请领单撤回
    - 请领审核
    - 请领复核
    - 根据id获取请领单信息
    - 根据id和状态获取请领单信息
  goodsRequest_02:
    - 删除请领单
  invoice_Manual:
    - 根据发票查询发票明细
    - 电子发票红冲
    - 手工发票红冲
    - 修改手工红冲发票
  invoice_finStates:
    - 分页获取销后结算开票列表
    - 销后结算发票上传
    - 销后结算待修改详情
    - 销后结算修改
  invoice_sync:
    - 查询列表--待审核
    - 待审核导出
    - 查询列表--待验收
    - 获取所有开票企业
    - 待验收导出
    - 查询列表--待支付
    - 待支付导出
    - 查询列表--支付完成
    - 支付完成导出
    - 查询列表--驳回
    - 驳回导出
    - 发票审核
    - 发票验收
    - 发票支付
    - 发票作废
    - 编辑电子发票
    - 分页获取货票同行开票列表
    - 货票同行发票上传
    - 根据发票号码查询蓝票
    - 查询发票汇总信息
    - 货票同行原票待修改详情
    - 货票同行原票修改
    - 查看转账凭证

  statement:
    - 查询条件分页查询
    - 分页显示结算单组
    - 确认并提交结算单
    - 审批结算单
    - 复核结算单
    - 复核结算单
    - 重新生成结算单
    - 上传发票
    - 加载发票
    - 导出结算单数据
    - 获取结算单打印数据
    - 导出托管商结算单

  cost_invoicing:
    - 分页查询
    - 查询成本明细
    - 导出
    - 列表查询
    - 导出

  globalSearch:
    - 获取查询类型列表
    - 全局搜索
    - 根据条码查询商品生命周期
    - 根据条码查询商品生命周期
    - 根据GS1查询商品信息

  gsp_history:
    - 产品注册证提醒
    - 企业证照提醒
    - 获取商品历史库存列表
    - 获取定数包历史库存列表
    - 获取手术套包历史库存列表

  hospital:
    - 设置当前医院
    - 医院列表
    - 根据id获取医院院区详情
    - 获取医院院区列表
    - 获取医院职务列表


  std95GoodsCategory_goodsQuantityUnits:
    - 获取所有分类
    - 获取根节点列表
    - 获取每个根节点下面的子列表
    - 获取商品计量单位信息列表

  upload:
    - 导入供应商信息
    - 导入生产商信息
    - 导入一级供应商信息
    - 导入商品和授权信息
    - 导入科室信息

  Statistic:
    - 获取所有可以访问的报表
    - 获取单个报表的源数据
    - 查询数据
    - 导出数据
    - 分页查询科室试剂库存报表
    - 导出试剂库存报表
    - 试剂库存记录
    - 试剂库存记录
    - 分页查询科室消耗汇总数据
    - 导出科室消耗汇总报表数据
    - 分页获取入库汇总列表
    - 导出入库汇总报表数据
    - 查询科室/全院月度金额报表
    - 查询科室/全院月度消耗的同比和环比
    - 查询全院科室消耗对照
    - 查询科室/全院商品消耗对照
    - 查询耗材消耗排名
    - 各科室耗材采购总金额按月排名
    - 查询超过基准值的科室
    - 各个流程之间时间耗时
    - 退货流程各环节时间耗时
    - 查询新增商品
    - 查询各科室增长率对比
    - 查询医院采购总金额
    - 查询各科室采购总金额
    - 查询供应商/一级供应商月度消耗金额
    - 查询一级供应商所有供应商消耗对照
    - 查询全院每月消耗的同比、环比
    - 供应商耗时查询
    - 查询新增供应商
    - 中心库退货统计
    - 导出中心库退货统计
    - 仓库人员的平均工作耗时
    - 未知接口

  get_Bag_Pkg:
    - 根据id获取普通套包详情
    - 分页获取普通套包列表
    - 导出定数包
    - 普通套包条码打印
    - 查询部门绑定的定数包
    - 查询部门未绑定的定数包
    - 查询部门所有仓库设置的定数包上下限
    - 根据id获取手术套包详情
    - 根据id获取手术套包详情
    - 导出手术套包
    - 分页获取部门绑定的手术套包列表
    - 查询未绑定手术套包



  warehouses:
    - 添加仓库
    - 更新仓库信息
    - 根据id获取仓库详情
    - 分页获取仓库列表
    - 查询部门的仓库信息
    - 查询部门的仓库信息
    - 根据当前用户查询用户部门下所有的仓库
    - 查询中心仓库
    - 推送组列表
    - 仓库货位汇总查询
    - 仓库货位汇总导出
    - 新增库区
    - 更新库房信息
    - 根据库房id获取详情
    - 分页获取库房列表
    - 根据仓库id获取库房列表
    - 查询中心库的库房列表
    - 删除库房信息
    - 新增货架
    - 更新货架信息
    - 根据id获取货柜详情
    - 分页获取货柜列表
    - 根据库房id获取货柜列表
    - 根据id删除货柜信息





  jpush:
    - 保存alias

  deliveryOrder:
    - 查询推送单列表
    - 查询推送单明细
    - 推送单复核
    - 推送单撤销复核
    - 选择推送人
    - 打印推送单
    - 批量复核推送单
    - 推送单导出

  medicalAdvice:
    - 分页查询医嘱收费汇总
    - 导出医嘱收费汇总
    - 根据病例号/病人号/医嘱号 查询医嘱列表
    - 根据医嘱id查询该医嘱上已消耗的物资列表
    - 分页查询医嘱信息(用于手术请领绑定医嘱)
    - 分页查询医嘱信息
    - 提交医嘱(锁定)
    - 查询医嘱收费详情(用于医嘱编辑)
    - 医嘱反消耗
    - 分页查询手术管理列表
    - 查看手术详情，包括手术信息，消耗物资信息
    - 导出手术详情

  message:
    - weChat拉取数据
    - pullMessage拉取数据
    - 获得未读消息
    - 操作消息
    - 消息改变未读为已读(批量)
    - 分页获取消息列表
    - 获取用户消息类型
    - 根据id设置消息已读
    - 根据id批量删除消息
    - 获取最新一条未读消息
    - 获取前rank条消息
    - 获取消息和权限信息
    - 新增消息和权限的信息
    - 更新权限列表
    - 根据id删除用户的权限信息

  acceptance_Check_01:
    - 科室验收单
    - 验收单明细
    - 打印验收单
    - 验收
    - 取消验收
    - 验收完成
    - 单个验收

  diagnosisProject:
    - 新增诊疗项目
    - 修改诊疗项目
    - 根据id查询诊疗项目
    - 启用诊疗项目
    - 禁用诊疗项目
    - 列表
    - 导出诊疗项目

  diagnosis_project_department:
    - 查询科室诊疗项目列表
    - 绑定
    - 解绑

  doctor:
    - 根据id查询医生信息
    - 根据医生查询手术请领

  patient:
    - 根据id查询病人信息
    - 根据病人查询手术请领
    - 查询病人普通消耗
    - pda待办任务数量

  pickOrder:
    - 生成拣货单
    - 查询拣货单列表
    - 查询拣货单明细
    - 打印拣货单
    - 拣货
    - 根据仓库批量生成拣货单
    - 取消拣货单
    - 提前完成拣货单
    - 查询待拣货列表
    - 取消待拣货数据

  usersPermissions:
    - 新增用户
    - 更新用户信息
    - 根据id获取用户详情
    - 用户启用/禁用
    - 根据组织Id获取用户列表
    - 修改密码
    - 重置密码
    - 查询拣货员列表
    - 查询推送员列表
    - 查询用户基本信息
    - 新增角色
    - 更新角色信息
    - 根据id获取角色详情
    - 角色启用/禁用
    - 分页获取角色列表
    - 根据type获取角色列表
    - 新增权限数据
    - 更新权限信息
    - 根据id获取权限详情
    - 获取权限列表
    - 根据医院查询用户的权限
    - 根据医院查询菜单
    - 查询菜单权限树
    - 重新加载接口权限
    - 角色绑定到用户
    - 用户解绑角色

  printer:
    - 查询科室打印机列表

  processingOrder:
    - 加工单分页查询
    - 查询详情
    - 制作加工单
    - 加工单生成拣货单
    - 加载定数包加工信息
    - 加载定数包加工信息(在一个列表中)
    - 加载手术套包加工信息
    - 加载手术套包加工信息(在一个列表中)
    - 制作定数包
    - 批量制作定数包
    - 制作手术套包
    - 删除加工单
    - 查询要加工的手术套包中的商品
    - 查询未组包的拣货单明细



  usersPermissions_01:
    - 获取用户列表



  logicStockTakingOrder:
    - 新增逻辑库盘库单
    - 删除逻辑库盘库单
    - 提交逻辑库盘库单
    - 逻辑库盘库单审核通过
    - 逻辑库盘库单审核不通过
    - 查询逻辑库盘库单列表
    - 查询逻辑库盘库单
    - 打印逻辑库盘库单

  logicStockOperation_logicStock:
    - 分页查询库存日志
    - 库存日志导出
    - 手工处理
    - 逻辑仓库库存分页查询
    - 逻辑库库存导出













test_case_1:
  GetAudit:
    - 分页查询审计记录
    - 查询操作历史
    - 创建角色
